### ISSUE TITLE
microsoft/application-insights is abandoned.

### ISSUE THREAD

**Issue by tomme87** [app-insights-php/client#21]
Since [microsoft/application-insights](https://github.com/microsoft/ApplicationInsights-PHP) is abandoned, is there any plans on not relying on that SDK?

**Comment by norberttech** [comment]
hey @tomme87 this library is a wrapper for Microsoft client mostly because the original one is abandoned. 
Personally, I don't have any plans to replace it (at least for now) however it might happen if the API of app insights service will change. 
If anyone would like to pick up this project and start working on replacing the original client with our own implementation that would be a bit more generic (using for example PSR for HTTP client to not force this lib HTTP client implementation dependency) I would be more than happy to help.

**Comment by norberttech** [comment]
I'm closing this one for now but if anyone would like to pick it up and add whole communication with the API directly to this client, I would be more than happy to help
